apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: ticketing-dev-
namespace: ticketing-dev
resources:
  - ../../base
patches:
  - path: patch-deploy.yaml
images:
  - name: daihuu/auth
    newName: daihuu/auth
    newTag: latest
  - name: daihuu/client
    newName: daihuu/client
    newTag: latest
  - name: daihuu/expiration
    newName: daihuu/expiration
    newTag: latest
  - name: daihuu/orders
    newName: daihuu/orders
    newTag: latest
  - name: daihuu/payments
    newName: daihuu/payments
    newTag: latest
  - name: daihuu/tickets
    newName: daihuu/tickets
    newTag: latest
