apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-mongo-depl.yaml
  - orders-mongo-depl.yaml
  - payments-mongo-depl.yaml
  - tickets-mongo-depl.yaml
  - expiration-redis-depl.yaml
  - nats-depl.yaml
